version: '3.8'

services:
  opentelemetry-collector:
    image: "otel/opentelemetry-collector-contrib:0.118.0"
    command: ["--config=/conf/relay.yaml"]
    ports:
      - "6831:6831/udp"
      # - "14250:14250"
      # - "14268:14268"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
    volumes:
      - ./config/relay.yaml:/conf/relay.yaml
    env_file:
      - .env

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "4317:4317"
      - "9411:9411"
